---
title: "R Notebook"
output: html_notebook
---
###### Panel 2 Change Section ########

    observeEvent(input$details,{
      if (input$details){
        updateTabsetPanel(session, "Panel1", selected = "Panel2")
        
        data_target <- data.frame(Longitude = posi()$lng, Latitude = posi()$lat)
        coordinates(data_target) <- ~Longitude + Latitude
        proj4string(data_target) <- proj4string(nyc_nbhd)
        matches <- over(data_target, nyc_nbhd)
        matches <- mathches[,c(1,3)]
        colnames(matches) <- c("nbhd","boro")
      }
      
      output$plot <- renderPlot({
        if (nrow(match1) == 0){
          return(NULL)
        }
        
        
      })
    })
    
    
######### Panel 1 health condition Section #########


    if (input$healthp == "All"){
      ## when health condition is ALL
      tree_num <- data_2015 %>% 
        group_by(postcode) %>% 
        count(health) %>% 
        ungroup() %>% 
        mutate(region = as.character(postcode), value = n) %>% 
        select(region, value) %>% 
        filter(region %in% valid_region)
    }
    else if (input$healthp == "Good"){
      ## when health condition is GOOD
      tree_num <- data_2015 %>% 
        group_by(postcode) %>% 
        count(health) %>% 
        ungroup() %>% 
        filter(health == "Good") %>%
        mutate(region = as.character(postcode), value = n) %>% 
        select(region, value) %>% 
        filter(region %in% valid_region)
    }
    else if (input$healthp == "Fair"){
      ## when health condition is FAIR
      tree_num <- data_2015 %>% 
        group_by(postcode) %>% 
        count(health) %>% 
        ungroup() %>% 
        filter(health == "Fair") %>%
        mutate(region = as.character(postcode), value = n) %>% 
        select(region, value) %>% 
        filter(region %in% valid_region)
    }
    else if (input$healthp == "Poor"){
      ## when health condition is POOR
      tree_num <- data_2015 %>% 
        group_by(postcode) %>% 
        count(health) %>% 
        ungroup() %>% 
        filter(health == "Poor") %>%
        mutate(region = as.character(postcode), value = n) %>% 
        select(region, value) %>% 
        filter(region %in% valid_region)
    }
    else{
      ## when health condition is DEAD
      tree_num <- data_2015 %>% 
        group_by(postcode) %>% 
        count(health) %>% 
        ungroup() %>% 
        filter(health == "Dead") %>%
        mutate(region = as.character(postcode), value = n) %>% 
        select(region, value) %>% 
        filter(region %in% valid_region)
    }